# Generated by Django 3.0.4 on 2020-04-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyber_alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendquery', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=100)),
                ('transid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyber_alert.GiverTransaction')),
            ],
        ),
    ]
